In [8]:
import torch
from torch import nn

In [9]:
class myFirstLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()


layer = myFirstLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [12]:
net = nn.Sequential(nn.Linear(8, 16), myFirstLayer())
net(torch.rand(1, 8))

tensor([[-0.4352,  0.5869,  0.1715,  0.0267, -0.3095,  0.5091, -0.4998, -0.1623,
         -0.0100,  0.0348, -0.6428,  0.2790,  0.5074,  0.3569, -0.2986, -0.1141]],
       grad_fn=<SubBackward0>)

In [23]:
class myLinear(nn.Module):
    def __init__(self, in_units, out_units):
        super().__init__()
        self.weight = torch.rand(in_units, out_units)
        self.bias = torch.rand(out_units)

    def forward(self, X):
        h = torch.matmul(X, self.weight.data) + self.bias.data
        return nn.functional.relu(h)

ml = myLinear(8, 16)
ml(torch.tensor([-1, -2, 3., 2.1, -1.2, 2, 4, 5]))

tensor([ 9.0912,  2.5225,  8.2572,  1.7530,  3.8271,  4.7539,  9.0255,  5.7048,
         6.3211, 10.9447,  3.1563,  5.4019,  3.7670,  6.6258,  5.5850,  8.3911])

In [24]:
ml.weight, ml.bias

(tensor([[0.5951, 0.0593, 0.0016, 0.6765, 0.9281, 0.5593, 0.6187, 0.0920, 0.7601,
          0.3283, 0.8766, 0.7334, 0.4496, 0.3782, 0.6352, 0.3742],
         [0.1519, 0.9444, 0.9957, 0.8919, 0.6430, 0.0583, 0.0825, 0.4802, 0.6916,
          0.5790, 0.6364, 0.4376, 0.1574, 0.6311, 0.7402, 0.1338],
         [0.3650, 0.0732, 0.3082, 0.0054, 0.3590, 0.9079, 0.9388, 0.2425, 0.7290,
          0.4315, 0.2925, 0.8197, 0.1161, 0.3512, 0.1927, 0.6965],
         [0.9384, 0.7163, 0.1259, 0.0448, 0.3653, 0.0970, 0.1629, 0.7062, 0.4961,
          0.7681, 0.2672, 0.3617, 0.0962, 0.0972, 0.8350, 0.5169],
         [0.3744, 0.4523, 0.4586, 0.2184, 0.1665, 0.0135, 0.9018, 0.3339, 0.0861,
          0.2733, 0.0336, 0.2791, 0.0890, 0.0839, 0.7446, 0.3313],
         [0.3630, 0.0948, 0.2438, 0.6222, 0.9770, 0.4031, 0.9268, 0.4732, 0.3869,
          0.6928, 0.1599, 0.6499, 0.5823, 0.6801, 0.6322, 0.3295],
         [0.4991, 0.0234, 0.9181, 0.3547, 0.2044, 0.3641, 0.3831, 0.7808, 0.0824,
          0.9713, 0.6394